//! Step 4½a-2 — Hard gate 5, the settings TOML byte gate (design §3.4), against the C++ oracle
//! `oracle_dump_settings` (`src/tools/oracle_dump/settings_dump.cpp`, regenerated by
//! `gen_settings_golden.sh`). `golden/settings/corpus.txt` lists every input; the C++ tool and
//! this test both read it.
//!
//! - **G5a**: `rust_save(rust_load(I)) == cpp_save(cpp_load(I))` for every corpus input `I`.
//! - **G5b**: every C++-saved file `O` round-trips — `rust_save(rust_load(O)) == O` — and
//!   `rust_load(O) == rust_load(I)`.
//! - **G5c** (T3): the gameplay bytes and both `UpdateHash` vectors.
//!
//! Setups load like `Gfx::LoadSettings` (a fresh `Settings`, then `FromToml`); profiles like
//! `LoadProfile` over a bare `WormSettings()` — the tool's starting values (design §9.3.1).

use std::collections::BTreeMap;
use std::path::Path;

use scenario::settings::{Settings, WormSettings};
use scenario::settings_toml::{
    gameplay_toml, load_profile, settings_from_toml, settings_to_toml, update_hash,
    worm_settings_to_toml, worm_update_hash,
};

const GOLDEN: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/golden/settings");
const REPO: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// A file under `golden/settings/`.
fn golden(name: &str) -> String {
    read(&Path::new(GOLDEN).join(name))
}

/// One `corpus.txt` entry: `<kind> <id> [<path>]`, `<path>` = the rest of the line.
struct Entry {
    kind: String,
    id: String,
    path: Option<String>,
}

impl Entry {
    fn is_setup(&self) -> bool {
        self.kind == "setup" || self.kind == "default-setup"
    }

    /// The input file's text (repo-root-relative path).
    fn input(&self) -> String {
        read(&Path::new(REPO).join(self.path.as_deref().expect("an input path")))
    }

    /// `Gfx::LoadSettings`: a fresh `Settings`, then `FromToml` — or `Settings()` itself.
    fn load_setup(&self) -> Settings {
        match self.kind.as_str() {
            "default-setup" => Settings::default(),
            "setup" => {
                settings_from_toml(&self.input()).unwrap_or_else(|e| panic!("{}: {e}", self.id))
            }
            k => panic!("{}: not a setup entry ({k})", self.id),
        }
    }

    /// `LoadProfile` over a bare `WormSettings()` — or `WormSettings()` itself.
    fn load_profile(&self) -> WormSettings {
        let mut ws = WormSettings::default();
        match self.kind.as_str() {
            "default-profile" => {}
            "profile" => {
                load_profile(&self.input(), &mut ws).unwrap_or_else(|e| panic!("{}: {e}", self.id))
            }
            k => panic!("{}: not a profile entry ({k})", self.id),
        }
        ws
    }

    /// The file C++ saved for this entry.
    fn saved_name(&self) -> String {
        if self.is_setup() {
            format!("{}.cfg", self.id)
        } else {
            format!("{}.toml", self.id)
        }
    }
}

fn corpus() -> Vec<Entry> {
    golden("corpus.txt")
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .map(|l| {
            let mut it = l.splitn(3, ' ');
            Entry {
                kind: it.next().expect("kind").to_string(),
                id: it.next().expect("id").to_string(),
                path: it.next().map(str::to_string),
            }
        })
        .collect()
}

fn entry(id: &str) -> Entry {
    corpus()
        .into_iter()
        .find(|e| e.id == id)
        .unwrap_or_else(|| panic!("no corpus entry {id}"))
}

/// Byte equality, reporting the first differing line.
fn assert_same(label: &str, got: &str, want: &str) {
    if got == want {
        return;
    }
    let g: Vec<&str> = got.split('\n').collect();
    let w: Vec<&str> = want.split('\n').collect();
    let i = g
        .iter()
        .zip(&w)
        .position(|(a, b)| a != b)
        .unwrap_or(g.len().min(w.len()));
    panic!(
        "{label}: rust {} bytes vs C++ {} bytes; first difference at line {}:\n  rust: {:?}\n  c++:  {:?}",
        got.len(),
        want.len(),
        i + 1,
        g.get(i),
        w.get(i)
    );
}

#[test]
fn g5a_rust_load_and_save_equals_cpp_load_and_save() {
    let entries = corpus();
    assert_eq!(entries.len(), 21, "corpus.txt entries");
    for e in &entries {
        let got = if e.is_setup() {
            settings_to_toml(&e.load_setup())
        } else {
            worm_settings_to_toml(&e.load_profile())
        };
        assert_same(
            &format!("G5a {} ({})", e.id, e.kind),
            &got,
            &golden(&e.saved_name()),
        );
    }
}

#[test]
fn g5b_cpp_saved_files_round_trip_through_rust() {
    for e in &corpus() {
        let saved = golden(&e.saved_name());
        if e.is_setup() {
            let back = settings_from_toml(&saved).unwrap_or_else(|err| panic!("{}: {err}", e.id));
            assert_same(&format!("G5b {}", e.id), &settings_to_toml(&back), &saved);
            assert_eq!(
                back,
                e.load_setup(),
                "G5b {}: rust_load(O) == rust_load(I)",
                e.id
            );
        } else {
            let mut back = WormSettings::default();
            load_profile(&saved, &mut back).unwrap_or_else(|err| panic!("{}: {err}", e.id));
            assert_same(
                &format!("G5b {}", e.id),
                &worm_settings_to_toml(&back),
                &saved,
            );
            assert_eq!(
                back,
                e.load_profile(),
                "G5b {}: rust_load(O) == rust_load(I)",
                e.id
            );
        }
    }
}

/// `hashes.txt`: `<kind> <id> <hash %016x>` → id ↦ hash; the `xxh3-empty -` KAT sits under `"-"`.
fn hashes() -> BTreeMap<String, u64> {
    golden("hashes.txt")
        .lines()
        .map(|l| {
            let cols: Vec<&str> = l.split(' ').collect();
            assert_eq!(cols.len(), 3, "hashes.txt line {l:?}");
            (
                cols[1].to_string(),
                u64::from_str_radix(cols[2], 16).expect("hex hash"),
            )
        })
        .collect()
}

#[test]
fn g5c_gameplay_bytes_and_update_hash_match_cpp() {
    let hashes = hashes();
    assert_eq!(
        hashes["-"], 0x2d06_8005_38d3_94c2,
        "C++ XXH3_64 of zero bytes == the twox-hash known answer"
    );
    let entries = corpus();
    assert_eq!(
        hashes.len(),
        entries.len() + 1,
        "one hash per corpus entry + the KAT"
    );
    for e in &entries {
        let want = hashes[&e.id];
        if e.is_setup() {
            let s = e.load_setup();
            assert_same(
                &format!("G5c {} gameplay", e.id),
                &gameplay_toml(&s),
                &golden(&format!("{}.gameplay.toml", e.id)),
            );
            assert_eq!(update_hash(&s), want, "G5c {}: Settings::UpdateHash", e.id);
        } else {
            let ws = e.load_profile();
            assert_eq!(
                worm_update_hash(&ws),
                want,
                "G5c {}: WormSettings::UpdateHash",
                e.id
            );
        }
    }
}

#[test]
fn milestone_the_corpus_covers_every_shipped_file_and_the_4_5a1_sidecars() {
    let entries = corpus();
    let paths: Vec<&str> = entries.iter().filter_map(|e| e.path.as_deref()).collect();
    for (dir, ext) in [("data/Setups", ".cfg"), ("data/Profiles", ".toml")] {
        let mut seen = 0;
        for file in std::fs::read_dir(Path::new(REPO).join(dir)).expect("shipped dir") {
            let name = file
                .expect("dir entry")
                .file_name()
                .into_string()
                .expect("utf-8");
            if name.ends_with(ext) {
                seen += 1;
                let rel = format!("{dir}/{name}");
                assert!(
                    paths.contains(&rel.as_str()),
                    "{rel} is shipped but not in corpus.txt"
                );
            }
        }
        assert!(seen > 0, "{dir} has shipped files");
    }
    for v in ["killemall", "scales", "gametag"] {
        let rel = format!("rust/oracle-tests/golden/sim_slice4_5a_{v}_setup.cfg");
        assert!(paths.contains(&rel.as_str()), "{rel} is in corpus.txt");
    }
    let count = |kind: &str| entries.iter().filter(|e| e.kind == kind).count();
    assert_eq!(
        (
            count("default-setup"),
            count("default-profile"),
            count("setup"),
            count("profile")
        ),
        (1, 1, 9, 10)
    );
}

#[test]
fn milestone_cpp_cross_checks_and_layout() {
    // The shipped legacy liero.cfg loads as exactly Settings() (design §2.1): same bytes, hash.
    assert_eq!(golden("liero.cfg"), golden("defaults.cfg"));
    let h = hashes();
    assert_eq!(h["liero"], h["defaults"]);
    assert_ne!(
        h["orbmit"], h["defaults"],
        "orbmit changes four gameplay fields"
    );
    assert_ne!(
        h["quoting"], h["defaults"],
        "tc and levelFile are in the gameplay subset"
    );
    // The 4½a-1 generator wrote its sidecars in toml++'s canonical layout (T0 Step 5).
    for v in ["killemall", "scales", "gametag"] {
        let sidecar = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join(format!("golden/sim_slice4_5a_{v}_setup.cfg"));
        assert_eq!(
            golden(&format!("sidecar_{v}.cfg")),
            read(&sidecar),
            "sidecar {v}"
        );
    }
    // Design §9.3.3: weapTable is the only multiline array; 3 worm tables x 5 inline arrays;
    // exactly one trailing newline.
    for e in corpus().iter().filter(|e| e.is_setup()) {
        let cfg = golden(&e.saved_name());
        assert!(
            cfg.contains("weapTable = [\n    "),
            "{}: weapTable is multiline",
            e.id
        );
        assert_eq!(cfg.matches(" = [ ").count(), 15, "{}: inline arrays", e.id);
        assert!(
            cfg.ends_with('\n') && !cfg.ends_with("\n\n"),
            "{}: one trailing newline",
            e.id
        );
    }
}

#[test]
fn milestone_every_quoting_rule_appears_in_the_cpp_bytes() {
    let cfg = golden("quoting.cfg");
    for want in [
        "tc = \"mix \\\"q\\\" 'a' \\\\x\"\n",
        "levelFile = \"del\\u007F\"\n",
        "name = \"O'Brien\"\n",
        "gamepadName = 'say \"hi\"'\n",
        "gamepadSerial = 'C:\\pads\\1'\n",
        "name = 'tab\there'\n",
        "gamepadName = 'Zo\u{e9}'\n",
        "gamepadSerial = \"a\\u2028b\"\n",
        "name = \"bell\\u0001esc\\u001B\"\n",
        "gamepadName = '''two\nlines'''\n",
        "gamepadSerial = '''it's\nmulti'''\n",
    ] {
        assert!(cfg.contains(want), "quoting.cfg lacks {want:?}");
    }
    let profile = golden("quoting_profile.toml");
    for want in [
        "name = \"cr\\rhere\"\n",
        "gamepadName = \"\"\"x\ny\\u0002\"\"\"\n",
        "gamepadSerial = '''back\\slash\nnext'''\n",
    ] {
        assert!(
            profile.contains(want),
            "quoting_profile.toml lacks {want:?}"
        );
    }
    assert!(golden("edge_profile.toml").contains("name = \"nel\\u0085Zo\u{e9}\"\n"));
}

#[test]
fn milestone_edge_inputs_load_with_the_toml_input_archive_semantics() {
    // edge.cfg — every value below is also C++'s (G5a compared the saved bytes).
    let s = entry("edge").load_setup();
    assert_eq!(s.lives, 15, "4294967311 -> static_cast<int32_t> 15");
    assert_eq!(s.game_mode, u32::MAX);
    assert_eq!(s.select_bot_weapons, u32::MAX);
    assert_eq!(s.max_bonuses, -1, "i64::MAX -> int32 -1");
    assert_eq!(s.loading_time, -7);
    assert_eq!(
        (s.blood, s.shadow, s.ai_traces),
        (100, true, false),
        "wrong types keep"
    );
    assert_eq!(
        &s.weap_table[..4],
        &[2, 0, 1, 0],
        "positional; a string element keeps 0"
    );
    let [p1, p2, np] = &s.worm_settings;
    assert_eq!(p1.name, "", "a wrongly typed name keeps ''");
    assert_eq!(p1.health, i32::MAX, "-2147483649 wraps");
    assert_eq!(
        p1.rgb,
        [252, 0, 4],
        "rgbDepth 7 => (v & 63) << 2; the 4th element ignored"
    );
    assert_eq!(p1.weapons, [5, 6, 7, 8, 9]);
    assert_eq!(
        p1.controls,
        [1, 2, 32, 34, 29, 42, 56],
        "short array: the default tail stays"
    );
    assert_eq!(p1.controls_ex, [u32::MAX; 8]);
    assert_eq!(
        p2.rgb,
        [240, 176, 240],
        "missing [player2]: the DEFAULT rgb is 6-bit expanded"
    );
    assert_eq!(np.rgb, [255, 0, 70], "8-bit values clamp");
    assert_eq!(np.weapons, [1; 5], "an empty array keeps every slot");

    let m = entry("missing_tables").load_setup();
    assert_eq!(m.lives, 3);
    for (i, v) in m.weap_table.iter().enumerate() {
        assert_eq!(
            *v as usize,
            i % 3,
            "weapTable[{i}]; the 41st entry is ignored"
        );
    }
    let rgbs: Vec<[i32; 3]> = m.worm_settings.iter().map(|ws| ws.rgb).collect();
    assert_eq!(rgbs, [[160, 160, 240], [240, 176, 240], [160, 160, 240]]);

    // array_player.cfg — design §3.2's positional reading, now confirmed by the real C++.
    let a = entry("array_player").load_setup();
    assert!(
        a.modern_colors && !a.record_replays,
        "slots 1 and 2 of `settings`"
    );
    assert_eq!(a.lives, 15, "no slot left for lives");
    let p = &a.worm_settings[0];
    assert_eq!((p.name.as_str(), p.health, p.controller), ("Pos", 55, 7));
    assert_eq!((p.random_name, p.color, p.input_device), (false, 3, 1));
    assert_eq!(
        (p.gamepad_name.as_str(), p.gamepad_serial.as_str()),
        ("g", "s")
    );
    assert_eq!((p.rgb, p.weapons), ([1, 2, 3], [9, 1, 1, 1, 1]));

    // edge_profile.toml — LoadProfile over a bare WormSettings().
    let q = entry("edge_profile").load_profile();
    assert_eq!(q.name, "nel\u{85}Zo\u{e9}");
    assert_eq!(
        (q.health, q.controller, q.color),
        (100, 1, 0),
        "keep; 2^32+1 -> 1; restored"
    );
    assert!(q.random_name, "a wrongly typed randomName keeps true");
    assert_eq!(q.weapons, [3, 1, 1, 1, 1]);
    assert_eq!(q.controls, [1, 2, 3, 4, 5, 6, 7]);
    assert_eq!(q.gamepad_controls, [u32::MAX, 12, 13, 14, 110, 10, 0, 9]);
    assert_eq!(q.rgb, [252, 0, 128], "no rgbDepth => 6-bit expansion");
}
