//! Step 4½a-2 — Hard gate 5, the settings TOML byte gate (design §3.4), against the C++ oracle
//! `oracle_dump_settings` (`src/tools/oracle_dump/settings_dump.cpp`, regenerated by
//! `gen_settings_golden.sh`). `golden/settings/corpus.txt` lists every input; the C++ tool and
//! this test both read it.
//!
//! - **G5a**: `rust_save(rust_load(I)) == cpp_save(cpp_load(I))` for every corpus input `I`.
//! - **G5b**: every C++-saved file `O` round-trips — `rust_save(rust_load(O)) == O` — and
//!   `rust_load(O) == rust_load(I)`.
//! - **G5c** (T3): the gameplay bytes and both `UpdateHash` vectors.
//!
//! Setups load like `Gfx::LoadSettings` (a fresh `Settings`, then `FromToml`); profiles like
//! `LoadProfile` over a bare `WormSettings()` — the tool's starting values (design §9.3.1).

use std::path::Path;

use scenario::settings::{Settings, WormSettings};
use scenario::settings_toml::{
    load_profile, settings_from_toml, settings_to_toml, worm_settings_to_toml,
};

const GOLDEN: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/golden/settings");
const REPO: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// A file under `golden/settings/`.
fn golden(name: &str) -> String {
    read(&Path::new(GOLDEN).join(name))
}

/// One `corpus.txt` entry: `<kind> <id> [<path>]`, `<path>` = the rest of the line.
struct Entry {
    kind: String,
    id: String,
    path: Option<String>,
}

impl Entry {
    fn is_setup(&self) -> bool {
        self.kind == "setup" || self.kind == "default-setup"
    }

    /// The input file's text (repo-root-relative path).
    fn input(&self) -> String {
        read(&Path::new(REPO).join(self.path.as_deref().expect("an input path")))
    }

    /// `Gfx::LoadSettings`: a fresh `Settings`, then `FromToml` — or `Settings()` itself.
    fn load_setup(&self) -> Settings {
        match self.kind.as_str() {
            "default-setup" => Settings::default(),
            "setup" => {
                settings_from_toml(&self.input()).unwrap_or_else(|e| panic!("{}: {e}", self.id))
            }
            k => panic!("{}: not a setup entry ({k})", self.id),
        }
    }

    /// `LoadProfile` over a bare `WormSettings()` — or `WormSettings()` itself.
    fn load_profile(&self) -> WormSettings {
        let mut ws = WormSettings::default();
        match self.kind.as_str() {
            "default-profile" => {}
            "profile" => {
                load_profile(&self.input(), &mut ws).unwrap_or_else(|e| panic!("{}: {e}", self.id))
            }
            k => panic!("{}: not a profile entry ({k})", self.id),
        }
        ws
    }

    /// The file C++ saved for this entry.
    fn saved_name(&self) -> String {
        if self.is_setup() {
            format!("{}.cfg", self.id)
        } else {
            format!("{}.toml", self.id)
        }
    }
}

fn corpus() -> Vec<Entry> {
    golden("corpus.txt")
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .map(|l| {
            let mut it = l.splitn(3, ' ');
            Entry {
                kind: it.next().expect("kind").to_string(),
                id: it.next().expect("id").to_string(),
                path: it.next().map(str::to_string),
            }
        })
        .collect()
}

fn entry(id: &str) -> Entry {
    corpus()
        .into_iter()
        .find(|e| e.id == id)
        .unwrap_or_else(|| panic!("no corpus entry {id}"))
}

/// Byte equality, reporting the first differing line.
fn assert_same(label: &str, got: &str, want: &str) {
    if got == want {
        return;
    }
    let g: Vec<&str> = got.split('\n').collect();
    let w: Vec<&str> = want.split('\n').collect();
    let i = g
        .iter()
        .zip(&w)
        .position(|(a, b)| a != b)
        .unwrap_or(g.len().min(w.len()));
    panic!(
        "{label}: rust {} bytes vs C++ {} bytes; first difference at line {}:\n  rust: {:?}\n  c++:  {:?}",
        got.len(),
        want.len(),
        i + 1,
        g.get(i),
        w.get(i)
    );
}

#[test]
fn g5a_rust_load_and_save_equals_cpp_load_and_save() {
    let entries = corpus();
    assert_eq!(entries.len(), 21, "corpus.txt entries");
    for e in &entries {
        let got = if e.is_setup() {
            settings_to_toml(&e.load_setup())
        } else {
            worm_settings_to_toml(&e.load_profile())
        };
        assert_same(
            &format!("G5a {} ({})", e.id, e.kind),
            &got,
            &golden(&e.saved_name()),
        );
    }
}

#[test]
fn g5b_cpp_saved_files_round_trip_through_rust() {
    for e in &corpus() {
        let saved = golden(&e.saved_name());
        if e.is_setup() {
            let back = settings_from_toml(&saved).unwrap_or_else(|err| panic!("{}: {err}", e.id));
            assert_same(&format!("G5b {}", e.id), &settings_to_toml(&back), &saved);
            assert_eq!(
                back,
                e.load_setup(),
                "G5b {}: rust_load(O) == rust_load(I)",
                e.id
            );
        } else {
            let mut back = WormSettings::default();
            load_profile(&saved, &mut back).unwrap_or_else(|err| panic!("{}: {err}", e.id));
            assert_same(
                &format!("G5b {}", e.id),
                &worm_settings_to_toml(&back),
                &saved,
            );
            assert_eq!(
                back,
                e.load_profile(),
                "G5b {}: rust_load(O) == rust_load(I)",
                e.id
            );
        }
    }
}
