//! T1 facit test — the `WideRollbackChecksum` cycle-0 word against the committed
//! `.lrp` corpus.
//!
//! The long fixture `golden/lrp_slice4e_long.lrp` (generated by the C++ `lrp_gen`
//! tool over `golden/lrp_slice4e_long_scenario.txt`) embeds a
//! `WideRollbackChecksum` word every 1050 frames (`replay.cpp:369`). The T0
//! reviewer extracted the two words: **`0x031057d7` at cycle 0** and
//! `0xf6211087` at cycle 1050. This test pins the **cycle-0** word — no `.lrp`
//! decode needed (that is T2/T3): it reconstructs the tick-0 `SimState` from the
//! *same* scenario the generator used (`scenario::load`, the bit-identical setup
//! the Phase-1 gate relies on) and reproduces the exact state the C++ writer
//! folded at cycle 0.
//!
//! The load-bearing subtlety: the C++ generator folds the checksum inside
//! `RecordFrame`, which runs AFTER it sets each worm's `control_states` from
//! `input[0]` (Down = 2) but BEFORE the first `ProcessFrame`. So the cycle-0
//! state is the fresh tick-0 state with `control_states = input[0]` and the
//! reader-tracked `prev_control_states` baseline still `0` for every worm.

use scenario::{load, Scenario};
use sim::state::ControlState;
use sim::wide_checksum::wide_rollback_checksum;
use std::path::Path;

const TC_ROOT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/TC/openliero");

/// The cycle-0 `WideRollbackChecksum` word embedded in `lrp_slice4e_long.lrp`
/// (extracted from the committed corpus by the T0 reviewer).
const CYCLE0_WORD: u32 = 0x0310_57d7;

#[test]
fn wide_checksum_tick0_matches_corpus_word() {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/golden/lrp_slice4e_long_scenario.txt"
    ))
    .expect("read golden/lrp_slice4e_long_scenario.txt");
    let scenario = Scenario::parse(&text).expect("scenario parses");
    assert_eq!(scenario.seed, 42, "corpus scenario uses seed 42");
    assert_eq!(scenario.worms.len(), 2, "corpus scenario has two worms");

    // Bit-identical tick-0 state (the setup the corpus generator mirrors).
    let mut loaded = load(Path::new(TC_ROOT), &scenario);

    // Reproduce the cycle-0 fold point: control_states = input[0] per worm,
    // prev_control_states baseline still 0. input(0, w) is Down = 2 for both.
    for (w_idx, worm) in loaded.state.worms.iter_mut().enumerate() {
        worm.control_states = ControlState::unpack(scenario.input(0, w_idx));
    }
    let prev_istates = vec![0u32; loaded.state.worms.len()];

    assert_eq!(loaded.state.cycles, 0, "fresh state is at cycle 0");
    assert_eq!(
        wide_rollback_checksum(&loaded.state, &prev_istates),
        CYCLE0_WORD,
        "tick-0 WideRollbackChecksum must equal the cycle-0 word embedded in the corpus"
    );
}
