//! Step 4½a-2 — a hand port of the subset of toml++ 3.4.0's `toml_formatter` that C++
//! settings persistence reaches (design §3.1, §3.3, §9.3.3). `cereal::TomlOutputArchive`
//! builds a `toml::table` and its destructor streams `out_ << root_ << "\n"`
//! (`toml_archive.hpp:47`), so the bytes C++ saves ARE this formatter's output plus one
//! newline. Sources (vcpkg `tomlplusplus` v3.4.0, `include/toml++/impl/`):
//! `toml_formatter.inl` (table layout, arrays, the 120-column rule), `formatter.inl`
//! (`print_newline`, `print_indent`, `print_string`), `forward_declarations.hpp`
//! (`control_char_escapes`), `unicode.hpp` / `unicode_autogenerated.hpp` (the control and
//! vertical-space classes).
//!
//! Only what the schema reaches is ported: a root holding key/values and/or non-inline
//! sub-tables of key/values, whose values are integers, booleans, strings and integer
//! arrays. `toml::table` is a `std::map<key, …, std::less<>>` (`table.hpp:224`), so keys come
//! out in byte order — a `BTreeMap<&str, _>`. The default `toml_formatter` flags apply
//! (`toml_formatter.hpp:83-91`): literal, multi-line, unicode and real-tab strings allowed,
//! `indentation` on with a 4-space indent. The gate is C++ output, not this reading
//! (`rust/oracle-tests/tests/settings_toml_golden.rs`).

use std::collections::BTreeMap;

/// A value the settings schema writes.
#[derive(Clone, Debug)]
pub(crate) enum Val<'a> {
    Int(i64),
    Bool(bool),
    Str(&'a str),
    Ints(Vec<i64>),
}

/// One table's key/values; the `BTreeMap` gives toml++'s byte-sorted key order.
pub(crate) type KeyVals<'a> = BTreeMap<&'static str, Val<'a>>;

/// `toml_formatter::print(array)`'s wrap limit (`toml_formatter.inl:185`).
const LINE_WRAP_COLS: usize = 120;
/// The `toml_formatter` indent string (`toml_formatter.hpp:100`): 4 columns.
const INDENT: &str = "    ";

/// `control_char_escapes` (`forward_declarations.hpp:127-160`), uppercase hex.
const CONTROL_CHAR_ESCAPES: [&str; 32] = [
    "\\u0000", "\\u0001", "\\u0002", "\\u0003", "\\u0004", "\\u0005", "\\u0006", "\\u0007", "\\b",
    "\\t", "\\n", "\\u000B", "\\f", "\\r", "\\u000E", "\\u000F", "\\u0010", "\\u0011", "\\u0012",
    "\\u0013", "\\u0014", "\\u0015", "\\u0016", "\\u0017", "\\u0018", "\\u0019", "\\u001A",
    "\\u001B", "\\u001C", "\\u001D", "\\u001E", "\\u001F",
];

/// `is_control_character` (`unicode.hpp:97-106`).
fn is_control(c: char) -> bool {
    (c as u32) <= 0x1F || c == '\u{7f}'
}

/// `is_non_ascii_vertical_whitespace` (`unicode_autogenerated.hpp:57-60`).
fn is_non_ascii_vertical_space(c: char) -> bool {
    matches!(c, '\u{85}' | '\u{2028}' | '\u{2029}')
}

/// A key `print(const key&)` emits bare (`print_string(k, false, true, false)`): the schema's
/// keys are all ASCII identifiers.
fn is_bare_key(k: &str) -> bool {
    !k.is_empty()
        && k.bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
}

/// `formatter::print_string` in value context (`formatter.inl:116-358`; `allow_multi_line`,
/// `allow_literal_whitespace` true, `allow_bare` false). Literal (`'…'`) unless the string has
/// a control character, or a `'` without a newline; a newline makes it multi-line (`'''…'''` /
/// `"""…"""`). Basic strings escape `"`, `\`, DEL and C0 controls (tab stays raw, a newline
/// only occurs in a multi-line string and stays raw) and the three non-ASCII vertical spaces;
/// everything else, UTF-8 included, is written raw.
pub(crate) fn quote_string(s: &str) -> String {
    if s.is_empty() {
        return "''".to_string();
    }
    let mut line_breaks = false;
    let mut single_quotes = false;
    let mut control = false;
    for c in s.chars() {
        match c {
            '\n' => line_breaks = true,
            '\t' => {}
            '\'' => single_quotes = true,
            c if is_control(c) || is_non_ascii_vertical_space(c) => control = true,
            _ => {}
        }
    }
    let multi_line = line_breaks;
    let literal = !control && (!single_quotes || multi_line);
    let quot = match (literal, multi_line) {
        (true, false) => "'",
        (true, true) => "'''",
        (false, false) => "\"",
        (false, true) => "\"\"\"",
    };
    let mut out = String::with_capacity(s.len() + 2 * quot.len());
    out.push_str(quot);
    if literal {
        out.push_str(s);
    } else {
        for c in s.chars() {
            match c {
                '"' => out.push_str("\\\""),
                '\\' => out.push_str("\\\\"),
                '\u{7f}' => out.push_str("\\u007F"),
                '\t' | '\n' => out.push(c),
                c if (c as u32) <= 0x1F => out.push_str(CONTROL_CHAR_ESCAPES[c as usize]),
                c if is_non_ascii_vertical_space(c) => {
                    out.push_str(&format!("\\u{:04X}", c as u32));
                }
                c => out.push(c),
            }
        }
    }
    out.push_str(quot);
    out
}

/// `toml_formatter_count_inline_columns` for an integer (`toml_formatter.inl:69-81`): 1 for 0,
/// else the digit count plus one for a `-`. C++ takes `log10(double)`, exact for every
/// |v| < 2^53 — all the i32/u32 values the schema stores.
fn int_columns(v: i64) -> usize {
    if v == 0 {
        1
    } else {
        usize::from(v < 0) + v.unsigned_abs().to_string().len()
    }
}

/// `toml_formatter_count_inline_columns` for an integer array (`toml_formatter.inl:46-59`):
/// `3 + Σ(width + 2)`, stopping once it reaches the wrap limit.
fn inline_columns(a: &[i64]) -> usize {
    if a.is_empty() {
        return 2;
    }
    let mut weight = 3;
    for &v in a {
        weight += int_columns(v) + 2;
        if weight >= LINE_WRAP_COLS {
            break;
        }
    }
    weight
}

/// The formatter state (`formatter.hpp:45-49`, `toml_formatter.hpp:51`).
struct Fmt {
    out: String,
    indent: i32,
    naked_newline: bool,
    pending_table_separator: bool,
}

impl Fmt {
    /// `formatter::attach` (`formatter.inl:68-73`): indent 0, nothing printed yet.
    fn new() -> Fmt {
        Fmt {
            out: String::new(),
            indent: 0,
            naked_newline: true,
            pending_table_separator: false,
        }
    }

    /// `print_newline` (`formatter.inl:82-89`): unforced, nothing is printed right after a
    /// newline (or at the very start).
    fn newline(&mut self, force: bool) {
        if !self.naked_newline || force {
            self.out.push('\n');
            self.naked_newline = true;
        }
    }

    /// `print_indent` (`formatter.inl:92-99`): nothing for an indent <= 0.
    fn print_indent(&mut self) {
        for _ in 0..self.indent {
            self.out.push_str(INDENT);
            self.naked_newline = false;
        }
    }

    /// `print_unformatted` (`formatter.inl:102-113`).
    fn raw(&mut self, s: &str) {
        self.out.push_str(s);
        self.naked_newline = false;
    }

    /// `print_pending_table_separator` (`toml_formatter.inl:120-128`): two forced newlines.
    fn pending_separator(&mut self) {
        if self.pending_table_separator {
            self.newline(true);
            self.newline(true);
            self.pending_table_separator = false;
        }
    }

    /// The key/value loop of `print(table)` (`toml_formatter.inl:250-272`).
    fn values(&mut self, kv: &KeyVals<'_>) {
        for (k, v) in kv {
            debug_assert!(is_bare_key(k), "schema keys are bare: {k:?}");
            self.pending_table_separator = true;
            self.newline(false);
            self.print_indent();
            self.raw(k);
            self.raw(" = ");
            match v {
                Val::Int(i) => self.raw(&i.to_string()),
                Val::Bool(b) => self.raw(if *b { "true" } else { "false" }),
                Val::Str(s) => {
                    let quoted = quote_string(s);
                    self.raw(&quoted);
                }
                Val::Ints(a) => self.array(a),
            }
        }
    }

    /// `print(array)` (`toml_formatter.inl:174-235`) for integer elements.
    fn array(&mut self, a: &[i64]) {
        if a.is_empty() {
            self.raw("[]");
            return;
        }
        let original_indent = self.indent;
        let bias = INDENT.len() * usize::try_from(original_indent.max(0)).unwrap_or(0);
        let multiline = inline_columns(a) + bias >= LINE_WRAP_COLS;
        self.raw("[");
        if multiline {
            if original_indent < 0 {
                self.indent = 0;
            }
            self.indent += 1; // indent_array_elements
        } else {
            self.raw(" ");
        }
        for (i, v) in a.iter().enumerate() {
            if i > 0 {
                self.raw(",");
                if !multiline {
                    self.raw(" ");
                }
            }
            if multiline {
                self.newline(true);
                self.print_indent();
            }
            self.raw(&v.to_string());
        }
        if multiline {
            self.indent = original_indent;
            self.newline(true);
            self.print_indent();
        } else {
            self.raw(" ");
        }
        self.raw("]");
    }
}

/// `toml_formatter::print()` on a root table (`toml_formatter.inl:376-393`, then
/// `print(table)` `:238-373`): the root's key/values, then each sub-table under a `[name]`
/// header, one blank line between tables. No trailing newline — `TomlOutputArchive`'s
/// destructor appends the only `"\n"`.
pub(crate) fn format_doc(
    values: &KeyVals<'_>,
    tables: &BTreeMap<&'static str, KeyVals<'_>>,
) -> String {
    let mut f = Fmt::new();
    f.indent -= 1; // `decrease_indent()`: root key/values and tables share one indent
    f.values(values);
    for (name, kv) in tables {
        debug_assert!(is_bare_key(name), "table names are bare: {name:?}");
        f.pending_separator();
        f.indent += 1; // indent_sub_tables
        f.print_indent();
        f.raw("[");
        f.raw(name);
        f.raw("]");
        f.pending_table_separator = true;
        f.values(kv);
        f.indent -= 1;
    }
    f.out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root(kv: KeyVals<'_>) -> String {
        format_doc(&kv, &BTreeMap::new())
    }

    #[test]
    fn plain_strings_are_literal_and_empty_is_two_single_quotes() {
        assert_eq!(quote_string(""), "''");
        assert_eq!(quote_string("openliero"), "'openliero'");
        assert_eq!(
            quote_string("Levels/modern_test.lev"),
            "'Levels/modern_test.lev'"
        );
        assert_eq!(quote_string("AI Joe"), "'AI Joe'");
    }

    #[test]
    fn double_quotes_backslashes_tabs_and_unicode_stay_literal() {
        assert_eq!(quote_string("say \"hi\""), "'say \"hi\"'");
        assert_eq!(quote_string("C:\\pads\\1"), "'C:\\pads\\1'");
        assert_eq!(
            quote_string("tab\there"),
            "'tab\there'",
            "real tabs are allowed"
        );
        assert_eq!(quote_string("Zo\u{e9}"), "'Zo\u{e9}'", "unicode is allowed");
    }

    #[test]
    fn a_single_quote_forces_a_basic_string() {
        assert_eq!(quote_string("O'Brien"), "\"O'Brien\"");
        assert_eq!(
            quote_string("mix \"q\" 'a' \\x"),
            "\"mix \\\"q\\\" 'a' \\\\x\""
        );
        assert_eq!(
            quote_string("it's\there"),
            "\"it's\there\"",
            "a tab stays raw in a basic string"
        );
    }

    #[test]
    fn control_characters_force_a_basic_string_with_the_cpp_escapes() {
        assert_eq!(
            quote_string("bell\u{1}esc\u{1b}"),
            "\"bell\\u0001esc\\u001B\""
        );
        assert_eq!(quote_string("cr\rhere"), "\"cr\\rhere\"");
        assert_eq!(quote_string("\u{8}\u{c}"), "\"\\b\\f\"");
        assert_eq!(quote_string("del\u{7f}"), "\"del\\u007F\"");
        assert_eq!(quote_string("a\u{2028}b"), "\"a\\u2028b\"");
        assert_eq!(
            quote_string("nel\u{85}Zo\u{e9}"),
            "\"nel\\u0085Zo\u{e9}\"",
            "only the vertical space is escaped; the \u{e9} stays raw"
        );
    }

    #[test]
    fn a_newline_makes_a_multi_line_string() {
        assert_eq!(quote_string("two\nlines"), "'''two\nlines'''");
        assert_eq!(
            quote_string("it's\nmulti"),
            "'''it's\nmulti'''",
            "a quote is fine in '''"
        );
        assert_eq!(quote_string("back\\slash\nnext"), "'''back\\slash\nnext'''");
        assert_eq!(
            quote_string("x\ny\u{2}"),
            "\"\"\"x\ny\\u0002\"\"\"",
            "newline + control: multi-line BASIC, the newline raw"
        );
        assert_eq!(quote_string("q\"\n\u{1}"), "\"\"\"q\\\"\n\\u0001\"\"\"");
    }

    #[test]
    fn arrays_wrap_when_the_estimate_reaches_120_columns() {
        // 3 + 38 * (1 + 2) = 117 < 120: inline, with inner spaces.
        let mut kv = KeyVals::new();
        kv.insert("a", Val::Ints(vec![0; 38]));
        let text = root(kv);
        assert_eq!(text.lines().count(), 1, "{text}");
        assert!(
            text.starts_with("a = [ 0, 0, ") && text.ends_with(", 0 ]"),
            "{text}"
        );
        // 3 + 39 * 3 = 120 >= 120: one element per line, 4-space indent, `]` on its own line.
        let mut kv = KeyVals::new();
        kv.insert("a", Val::Ints(vec![0; 39]));
        let mut want = String::from("a = [");
        for i in 0..39 {
            if i > 0 {
                want.push(',');
            }
            want.push_str("\n    0");
        }
        want.push_str("\n]");
        assert_eq!(root(kv), want);
    }

    #[test]
    fn integer_widths_count_digits_and_the_sign() {
        assert_eq!(inline_columns(&[0]), 6);
        assert_eq!(inline_columns(&[-1]), 7);
        assert_eq!(
            inline_columns(&[4_294_967_295; 8]),
            99,
            "the widest schema array stays inline"
        );
        assert_eq!(int_columns(i64::from(i32::MIN)), 11);
        assert_eq!(inline_columns(&[]), 2);
    }

    #[test]
    fn root_values_have_no_leading_or_trailing_newline() {
        let mut kv = KeyVals::new();
        kv.insert("name", Val::Str("x"));
        kv.insert("health", Val::Int(-3));
        kv.insert("randomName", Val::Bool(true));
        kv.insert("rgb", Val::Ints(vec![1, 2, 3]));
        assert_eq!(
            root(kv),
            "health = -3\nname = 'x'\nrandomName = true\nrgb = [ 1, 2, 3 ]"
        );
    }

    #[test]
    fn tables_get_headers_and_one_blank_line_between_them() {
        let mut settings = KeyVals::new();
        settings.insert("z", Val::Int(1));
        settings.insert("list", Val::Ints(vec![7; 40]));
        let mut player1 = KeyVals::new();
        player1.insert("k", Val::Bool(false));
        let mut tables = BTreeMap::new();
        tables.insert("settings", settings);
        tables.insert("player1", player1);
        let mut want = String::from("[player1]\nk = false\n\n[settings]\nlist = [");
        for i in 0..40 {
            if i > 0 {
                want.push(',');
            }
            want.push_str("\n    7");
        }
        want.push_str("\n]\nz = 1");
        assert_eq!(format_doc(&KeyVals::new(), &tables), want);
    }

    #[test]
    fn an_empty_array_is_two_brackets() {
        let mut kv = KeyVals::new();
        kv.insert("a", Val::Ints(Vec::new()));
        assert_eq!(root(kv), "a = []");
    }
}
