color = 0
controller = 0
controls = [ 0, 0, 0, 0, 0, 0, 0 ]
controlsEx = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
gamepadControls = [ 11, 12, 13, 14, 110, 10, 0, 9 ]
gamepadName = ''
gamepadSerial = ''
health = 100
inputDevice = 0
name = ''
randomName = true
rgb = [ 104, 104, 248 ]
rgbDepth = 8
weapons = [ 1, 1, 1, 1, 1 ]
