aiFrames = 140
aiMutations = 2
aiParallels = 3
aiTraces = false
allowViewingSpawnPoint = false
blood = 100
bonusTimeout = 0
flagsToWin = 20
gameMode = 4294967295
inputDelay = 1
levelFile = ''
lives = 15
loadChange = true
loadPowerlevelPalette = true
loadingTime = -7
map = true
maxBonuses = -1
namesOnBonuses = false
randomLevel = true
recordReplays = true
regenerateLevel = false
screenSync = true
selectBotWeapons = 4294967295
shadow = true
tc = 'openliero'
timeToLose = 600
weapTable = [
    2,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
]
zoneTimeout = 30
